version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    restart: always
